### ISSUE TITLE
Maybe rename the project?

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#16]
Maybe rename the project, so it doesn't get confused with the [original Copilot](https://addons.mozilla.org/en-US/firefox/addon/pardus-copilot/)?

Otherwise it'll be a constant faff explaining "no, this isn't the old Firefox extension, it's a new one written from scratch for Chrome" every single time. Plus, it's kinda not on to poach the name of an established project, even one as dead as that looks.

My own suggestion would be just "Copilot Next Generation", so _Copilot NG_. But anything's fine really. The S&M gimps should come up with something 😝

**Comment by valitas** [comment]
Related: it seems the extension already runs on Firefox, as is--I installed it manually, tested, works a charm (!). But if we're going to release an easy install for Firefox, it _does_ need a new name, because it will be on [addons.mozilla.org](https://addons.mozilla.org/) and there is already the old Copilot there.

While we're at it: a licence is also needed to publish there. As in MPL/GPL/MIT/BSD/whatever.

You need to decide on this for your code @BartKieviet. Me, I like to release my code to the public domain, but wouldn't mind going [MIT](https://opensource.org/licenses/mit-license.php) or [BSD](https://opensource.org/licenses/bsd-license.php) instead (it would be easier to pick those because they're predefined choices at project registration with Mozilla).

**Comment by BartKieviet** [comment]
MIT license looks fine. I'm all for open source.

**Comment by valitas** [comment]
Licensed in 0165c3bffa3b91aa313878ee8cbff143fb6b3b16

Now just need a name haha.

**Comment by valitas** [comment]
Done in 1b0429bf88427c5f797b65acd0e4f19bf5351264

Copilot is dead long live Bookkeeper.
