### ISSUE TITLE
Sync configuration across all user devices

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#19]
This may be as simple as switching from `storage.local` to `storage.sync`.

Investigating...

**Comment by valitas** [comment]
Well this is simple enough indeed. However, there is a problem. `storage.sync` has limits, and these are tight enough limits that can be a problem for us, see [chrome.storage docs](https://developer.chrome.com/extensions/storage#property-sync).

Of particular concern is `MAX_ITEMS`, the maximum number of storage keys that the extension could store. This means we'd be limited to tracking some 500 buildings across all three universes. It may be a reasonable limit, idk.

Still reviewing.

**Comment by BartKieviet** [comment]
Fixed in 32d6b50f0cb9462f0efdef3cbe02e37b6f0c2405
