### ISSUE TITLE
Track MOs

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#32]
From Fortress in the Pardus Forum:

> When I added the MOs that I trade to the book keeper it came with ?? in the level column and 0 in the commodities columns. I assume that the script has a problem reading the grid level, if possible could this please be fixed. If it cant be fixed would it be possible for you to make it so we could manually insert the grid level?

**Comment by valitas** [comment]
Depends on either #62 or #38 or both.

**Comment by BartKieviet** [comment]
Hurray, done in 2d75a29.
