### ISSUE TITLE
Track planets and starbases

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#33]
From Fortress in the Pardus Forum:

> I have one suggestion for the script, make it possible to add planets or SBs to the Bookkeeper. Possibly in its own table so that it doesn't interfere with the commodities of the buildings???

**Comment by BartKieviet** [comment]
From AC:
> is there anyway I can track f/w on a starbase with bookie?
> I would love to have a projection mode on just the f/w/e stocks in bases.
> so that I know when I have to upkeep bases
> and maybe have a message window that pops up if the projection indicates < 2 ticks of f/w left
> Yeah, or better yet, if I could select what I want to track on the base. So suppose on some bases I want f/w/e + droids + bots and on others I want f/w/e + HW + BWP

**Comment by BartKieviet** [comment]
Implemented (mostly) by 73725e20afbf4494ee3f5e71c588a60c581477ac
