### ISSUE TITLE
Provide auto buy/sell buttons for your own buildings

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#34]
Add buttons to the screen where you transfer goods to and from your own buildings, replicating the functionality of the buttons `Sell upkeep ->`, `<- Buy produced goods`, and `<- Auto Sell and Buy ->` that Pardus adds when you trade with other people's buildings.

**Comment by BartKieviet** [comment]
Done in 18cf553ec68523490a9e0e527c7d435e1e5fd42e.
