### ISSUE TITLE
Overview sorting is bugged

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#40]
Sorting by type, ticks left, and ticks now, is not working. This is a regression introduced in 6cd912481b91c148093dd2d85ba287ee70d0773d. I'll fix tomorrow, can't today 😪 

Also, sorting by location, while usable, is quirky. Thing is: it actually sorts by tile id. So, even though all buildings in a sector are kept together, and sorted by `y` coordinate, and then `x`, the sectors themselves are not in alphabetical order. It has behaved like this since sorting was added, but it really should be fixed.

**Comment by BartKieviet** [comment]
Fixed in e265d596f5d69e0d7df67296560806fc7f6bb4cb

Sorting by location still has to be changed.
