### ISSUE TITLE
Track space remaining in buildings

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#49]
From San Fran Dan in the Pardus forum:
> Any chance a column could be added for available tons of space? For farms, mines, neb plants, and other prone-to-overflow buildings, I sometimes prioritize by what's about to dump stock.

**Comment by BartKieviet** [comment]
Added small notice in the trade screen when a building is overflowing (40ad915fc6f7888f1830c003234bffbccaf5b618).
