### ISSUE TITLE
Don't auto-sell stim chips to planets

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#50]
Selling stim chips to planets is never something you'd want to do. It's always a mistake, it's never profitable, never will be. Yet Pardus' "auto sell" buttons will sell them anyway, to much frustration for you when you realise what it did. Let's see if we can keep it from doing that.

I don't know if this is even feasible (we'd have to "compete" with Pardus' own event handler). But just a reminder, let's think of it later.

**Comment by valitas** [comment]
Hint: when preview is enabled, we probably can clear those fields after Pardus' sets them. When it isn't... investigate if catching the [`submit`](https://developer.mozilla.org/en-US/docs/Web/Events/submit) event would work.

**Comment by BartKieviet** [comment]
Not truly fixed, but the new buttons added in e71250506f91a01a4c47bd617a8dd1900d06aa70 should help. Good enough for a close?

**Comment by BartKieviet** [comment]
I'm closing this, see above.
