### ISSUE TITLE
Close/open overview popup on keypress

### ISSUE THREAD

**Issue by BartKieviet** [BartKieviet/Bookkeeper#52]
Clicking is for people who like RSI. And this removes the *oh no my overview is now layed over my button* problem we get in SB/Planet trade.

**Comment by valitas** [comment]
This is mitigated by 8fbfb9e276824dea888f77bb919df6a6676e40bc, which introduced clicking anywhere outside the overlay box to close it. So now you can close the list even if the button is covered (which shouldn't happen anyway, with the new styles).

So this is not too urgent now, will remove the bug tag.

**Comment by BartKieviet** [comment]
I'm closing this since I don't want it no more 😝
