### ISSUE TITLE
Fix skittles when flying under blue stim influence

### ISSUE THREAD

**Issue by valitas** [BartKieviet/Bookkeeper#54]
From Commandaguy:
> Is there a way for all the ticks to be displayed on the buildings even when I'm using a blue stim?

I haven't tested myself, but apparently this is broken.

**Comment by valitas** [comment]
Info to fix, cheers @BartKieviet 

<img width="380" alt="span" src="https://user-images.githubusercontent.com/874729/31096818-df5835ca-a782-11e7-95c2-7bcd3bde3bc7.PNG">

**Comment by BartKieviet** [comment]
The BLDGTILE_XPATH is not correct due to the div direct after the td that is not present in non stimmed life.

I'm not touching the Xpath stuff with a ten-foot pole.
